package com.worldshare.mod.sync;

import java.nio.file.Path;
import java.util.UUID;

/**
 * Decides which files inside a Minecraft world folder are subject to sync.
 *
 * <p>Tracked files (synced):
 * <ul>
 *   <li>Region data: {@code region/*.mca}, {@code DIM-1/region/*.mca}, {@code DIM1/region/*.mca}</li>
 *   <li>Entity data: {@code entities/*.mca} and per-dimension equivalents (1.17+ split format)</li>
 *   <li>{@code level.dat} and {@code level.dat_old}</li>
 *   <li>Per-UUID files in {@code playerdata/}, {@code stats/}, {@code advancements/}
 *       — only the file matching {@link #ownPlayerUuid()}</li>
 *   <li>Custom data: {@code data/**}</li>
 *   <li>Per-world resource pack: {@code resources/**}</li>
 *   <li>Per-world data packs: {@code datapacks/**}</li>
 *   <li>Valkyrien Skies physics state: {@code v_data/**} (synced if present, optional)</li>
 * </ul>
 *
 * <p>Excluded:
 * <ul>
 *   <li>{@code session.lock} — Minecraft's local lock, not WorldShare's</li>
 *   <li>{@code icon.png} — auto-regenerated by Minecraft</li>
 *   <li>{@code *.log}, crash reports</li>
 *   <li>{@code *_old} backup files (Minecraft writes these for some, but {@code level.dat_old}
 *       is explicitly INCLUDED above as it's part of the standard rotation)</li>
 *   <li>Other player UUIDs in {@code playerdata/}, {@code stats/}, {@code advancements/}
 *       — those belong to other contributors, we never write them</li>
 * </ul>
 *
 * <p>The implementation is pure functions of the relativized path; no I/O.
 */
public final class TrackedPaths {

    private TrackedPaths() {
        // utility class
    }

    /**
     * Decide whether a given file inside a world folder should be synced
     * by this player.
     *
     * @param worldRoot     absolute path to the world folder root (e.g.
     *                      {@code .../saves/MyWorld})
     * @param file          absolute path to a file inside that world folder
     * @param ownPlayerUuid the local player's UUID; per-UUID files for any
     *                      other UUID will be excluded
     * @return true if the file should be tracked
     */
    public static boolean isTracked(final Path worldRoot,
                                    final Path file,
                                    final UUID ownPlayerUuid) {
        if (worldRoot == null || file == null) return false;
        if (!file.startsWith(worldRoot)) return false;

        // Use forward-slash form so the rules below are OS-independent.
        final String rel = worldRoot.relativize(file).toString().replace('\\', '/');
        if (rel.isEmpty()) return false;

        // Skip Minecraft's per-save session lock - it's local-only state.
        if (rel.equals("session.lock")) return false;

        // Skip the auto-generated world icon (regenerated each save).
        if (rel.equals("icon.png")) return false;

        // Skip log and crash files anywhere in the tree.
        if (rel.endsWith(".log")) return false;
        if (rel.contains("crash-reports/")) return false;

        // ---- INCLUDES ----

        // level.dat (and the backup rotation slot)
        if (rel.equals("level.dat") || rel.equals("level.dat_old")) return true;

        // Region files: overworld, nether, end, plus modded dimensions under DIM*/region/.
        // Match any */region/*.mca path.
        if (matchesRegion(rel)) return true;
        if (matchesEntities(rel)) return true;
        if (matchesPoi(rel)) return true;

        // Per-UUID files. Only the local player's own data syncs.
        if (matchesOwnUuid(rel, "playerdata", ".dat", ownPlayerUuid)) return true;
        if (matchesOwnUuid(rel, "stats", ".json", ownPlayerUuid)) return true;
        if (matchesOwnUuid(rel, "advancements", ".json", ownPlayerUuid)) return true;
        // Explicitly REJECT per-UUID files belonging to other players.
        if (matchesAnyUuidFile(rel, "playerdata", ".dat")
                || matchesAnyUuidFile(rel, "stats", ".json")
                || matchesAnyUuidFile(rel, "advancements", ".json")) {
            return false;
        }

        // Custom data: raids, structures, scoreboards, etc.
        if (rel.startsWith("data/")) return true;

        // Per-world resource pack and data packs.
        if (rel.startsWith("resources/")) return true;
        if (rel.startsWith("datapacks/")) return true;

        // Valkyrien Skies / Create Aeronautics physics state. Optional - sync if present.
        if (rel.startsWith("v_data/")) return true;

        // Anything not matched above is NOT tracked. This is intentional:
        // we whitelist rather than blacklist, so unknown files (e.g. logs from new
        // mods) don't get accidentally bundled into the sync.
        return false;
    }

    // ---- internal matchers ----

    /** Matches {@code region/*.mca}, {@code DIM-1/region/*.mca}, {@code DIM1/region/*.mca}, {@code dimensions/<ns>/<name>/region/*.mca}. */
    private static boolean matchesRegion(final String rel) {
        return (rel.endsWith(".mca") && rel.contains("/region/"))
                || (rel.startsWith("region/") && rel.endsWith(".mca"));
    }

    /** Matches {@code entities/*.mca} and dimensional equivalents. */
    private static boolean matchesEntities(final String rel) {
        return (rel.endsWith(".mca") && rel.contains("/entities/"))
                || (rel.startsWith("entities/") && rel.endsWith(".mca"));
    }

    /** Matches {@code poi/*.mca} and dimensional equivalents (point-of-interest data). */
    private static boolean matchesPoi(final String rel) {
        return (rel.endsWith(".mca") && rel.contains("/poi/"))
                || (rel.startsWith("poi/") && rel.endsWith(".mca"));
    }

    /**
     * Match {@code <subdir>/<UUID-no-dashes-or-with>.<ext>} for the local player's UUID.
     * Minecraft writes UUIDs in two formats:
     * - dashed: {@code 12345678-1234-1234-1234-123456789012.dat}  (for online accounts)
     * - this is the canonical form everywhere we've checked, but be lenient about hyphens
     */
    private static boolean matchesOwnUuid(final String rel,
                                          final String subdir,
                                          final String ext,
                                          final UUID ownUuid) {
        if (ownUuid == null) return false;
        if (!rel.startsWith(subdir + "/") || !rel.endsWith(ext)) return false;
        final String filename = rel.substring(subdir.length() + 1, rel.length() - ext.length());
        // Compare both with-and-without-dashes, just in case.
        final String dashed = ownUuid.toString();
        final String stripped = dashed.replace("-", "");
        return filename.equalsIgnoreCase(dashed) || filename.equalsIgnoreCase(stripped);
    }

    /**
     * @return true if {@code rel} looks like a per-UUID file inside the named subdir,
     *         regardless of which UUID. Used to explicitly reject other players' data.
     */
    private static boolean matchesAnyUuidFile(final String rel,
                                              final String subdir,
                                              final String ext) {
        if (!rel.startsWith(subdir + "/") || !rel.endsWith(ext)) return false;
        final String filename = rel.substring(subdir.length() + 1, rel.length() - ext.length());
        // Any sub-path with slashes inside the filename portion isn't a UUID file.
        if (filename.contains("/")) return false;
        // UUID is 32 hex chars (no dashes) or 36 chars (4 dashes). Quick heuristic.
        return filename.length() == 32 || filename.length() == 36;
    }
}
