package com.worldshare.mod.modmanager;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.util.ArrayList;
import java.util.List;

/**
 * POJO representation of {@code modpack.json}, the file that lives in the
 * Drive folder alongside {@code manifest.json} and {@code session.lock}.
 *
 * <p>Generated by the host via {@code /worldshare modpack generate} and read
 * by guests on the title screen to detect mods they're missing.
 *
 * <p>Excluded from generation: {@code minecraft}, {@code neoforge}, {@code forge},
 * {@code fml}, {@code worldshare}, {@code e4mc}. Mods running from class
 * directories (dev environment) are also skipped — generate command only works
 * meaningfully in a real production install.
 */
public final class ModpackManifest {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public String minecraft_version;
    public String loader;
    public String generated_at;
    public List<ModEntry> mods = new ArrayList<>();

    /** Single mod entry. */
    public static final class ModEntry {
        public String mod_id;
        public String display_name;
        public String version;
        public String sha1;
        public String filename;

        /** Direct CDN URL from Modrinth, or null if mod is not on Modrinth. */
        public String download_url;

        public ModEntry() {}

        public ModEntry(final String modId, final String displayName,
                        final String version, final String sha1,
                        final String filename, final String downloadUrl) {
            this.mod_id = modId;
            this.display_name = displayName;
            this.version = version;
            this.sha1 = sha1;
            this.filename = filename;
            this.download_url = downloadUrl;
        }
    }

    public String toJson() {
        return GSON.toJson(this);
    }

    public static ModpackManifest fromJson(final String json) {
        return GSON.fromJson(json, ModpackManifest.class);
    }
}